version: '3.4'

# Template.
x-template: &service-template
  restart: always
  env_file:
    - .env
  networks:
    - dnet

# Network.
networks:
  dnet:
    driver: bridge

# Services.
services:
  ingress:
    <<: *service-template
    image: "govueapp-ingress:${APP_VERSION}"
    ports:
      - "80:80"
  db:
    <<: *service-template
    image: "${MYSQL_CONTAINER}"
    ports:
      - "3306:3306"
  ui:
    <<: *service-template
    image: "govueapp-ui:${APP_VERSION}"
  api:
    <<: *service-template
    image: "govueapp-api:${APP_VERSION}"
