// Package api govueapp API
//
// This is the API for the sample notepad application in Vue and Go.
//
// Swagger 2.0 Spec - generated by [go-swagger](https://github.com/go-swagger/go-swagger)
//
// Schemes: http
// Host: localhost:8081
// BasePath: /
// Version: 1.0
//
// Consumes:
// - application/json
//
// Produces:
// - application/json
//
// SecurityDefinitions:
// token:
//   type: apiKey
//   name: Authorization
//   in: header
//   description: "In the 'Value' textbox below, please enter in the word 'Bearer', a space, and then paste in your token."
//
// swagger:meta
package api
